export { dedupByUrl, dedupByTitle, filterLowQuality, normalizeUrl } from './dedup.js';
export { scoreAndRank } from './scorer.js';
export { checkConfidenceBasket } from './scorer.js';
export type { ScoredResult, ConfidenceBasketResult, ConfidenceBasketOptions } from './scorer.js';
export { formatResults } from './format.js';
export { expandQuery } from './query-expander.js';
export { hasChinese, toTraditional, toSimplified, generateChineseVariants } from './chinese-optimizer.js';
export { enrichResults } from './enricher.js';
export type { EnrichOptions, EnrichResult } from './enricher.js';
export { detectLanguage } from './language-detector.js';
export type { DetectedLanguage } from './language-detector.js';
